/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GroupsImport } from './routes/groups'
import { Route as IndexImport } from './routes/index'
import { Route as MylistsIndexImport } from './routes/mylists/index'
import { Route as MylistsIdImport } from './routes/mylists/$id'

// Create/Update Routes

const GroupsRoute = GroupsImport.update({
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MylistsIndexRoute = MylistsIndexImport.update({
  path: '/mylists/',
  getParentRoute: () => rootRoute,
} as any)

const MylistsIdRoute = MylistsIdImport.update({
  path: '/mylists/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/groups': {
      preLoaderRoute: typeof GroupsImport
      parentRoute: typeof rootRoute
    }
    '/mylists/$id': {
      preLoaderRoute: typeof MylistsIdImport
      parentRoute: typeof rootRoute
    }
    '/mylists/': {
      preLoaderRoute: typeof MylistsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  GroupsRoute,
  MylistsIdRoute,
  MylistsIndexRoute,
])

/* prettier-ignore-end */
